##[>] 🤖🤖
spec:
  inputs:
    image:
      type: string
      default: $CI_IMAGE
    stage:
      type: string
      default: validate
    tags:
      type: array
      default:
        - gke-linux-amd64-small
---
generic:precommit-all:
  stage: $[[ inputs.stage ]]
  image: $[[ inputs.image ]]
  tags: $[[ inputs.tags ]]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
  script:
    - '[ -f shared/generic/make/generic.mk ] || ${BIN_CHE:-che} render-templates --profiles=generic/setup'
    - make generic-precommit-all
##[<] 🤖🤖
