# [>] autogenerated centralized/assets/generic generic/filesTracked/cheVariables
{{- range (localFile ".repo/upstream.env" | strings.Split "\n") }}
{{- if and (ne . "") (not (strings.HasPrefix "#" .)) }}
{{ index (strings.SplitN "=" 2 .) 0 }}: {{ index (strings.SplitN "=" 2 .) 1 }}
{{- end }}
{{- end }}
# [<] autogenerated centralized/assets/generic generic/filesTracked/cheVariables
