# yaml-language-server: $schema=https://gitlab.com/api/v4/projects/konradodwrot%2Fgo-modules/packages/generic/che-schema/{{ .var.CHE_SCHEMA_REF }}/che.schema.json
##[>] 🤖🤖
profilesDefinitions:
  'generic/filesTracked':
    options:
      autoDiscover: false
    include:
      makeCopies:
        - source: "git::gitlab.com/konradodwrot/centralized/assets/prose/human@{{ .var.CENTRALIZED_ASSETS_PROSE_HUMAN_REF }}//shared/license/LICENSE"
          dest: LICENSE
      renderTemplates:
        - source: "git::gitlab.com/konradodwrot/centralized/assets/prose/human@{{ .var.CENTRALIZED_ASSETS_PROSE_HUMAN_REF }}//prose/repos/{{ .var.repo }}/README.md.ontoRepo.tpl"
          dest: README.md

  'generic/filesUntracked':
    options:
      autoDiscover: false
    include:
      renderTemplates:
        - source: "git::gitlab.com/konradodwrot/centralized/assets/prose/common@{{ .var.CENTRALIZED_ASSETS_PROSE_COMMON_REF }}"
          options:
            skipAutoGeneratedHeader: true
          <<<:
            - source: //prose/repos/{{ .var.repo }}/purpose.md
              dest: assets/docs-agents/purpose.md
            - source: //templates/data
              dest: assets/data
              options:
                skipAutoGeneratedHeader: false
              <<<:
                - source: /makefile-agents.md.ontoRepo.tpl
                  dest: makefile.agents.md
                - source: /repo-structure.md.ontoRepo.tpl
                  dest: repo-structure.md
        - source: "git::gitlab.com/konradodwrot/centralized/assets/prose/ai@{{ .var.CENTRALIZED_ASSETS_PROSE_AI_REF }}//prose/repos/{{ .var.repo }}/AGENTS.md.ontoRepo.tpl"
          dest:
            - CLAUDE.md
            - path: AGENTS.md
              options:
                renderReferencedFiles: true

  'generic/env':
    options:
      autoDiscover: false
    include:
      renderTemplates:
        - source: ../../.che/tpl/repo-git-tracked/env.tpl
          dest:
            - path: .env
              options:
                writeType: mergeUpsert

  'generic/deps':
    options:
      autoDiscover: false
    include:
      installPackages:
        - make
        - lefthook
        - yq
        - glab

##[<] 🤖🤖