# yaml-language-server: $schema=https://gitlab.com/api/v4/projects/konradodwrot%2Fgo-modules/packages/generic/che-schema/{{ .var.CHE_SCHEMA_REF }}/che.schema.json
##[>] 🤖🤖
profilesDefinitions:
  'generic/filesTracked':
    type: repo-git-tracked
    options:
      autoDiscover: false
    include:
      makeCopies:
        - source:
            url: gitlab.com/konradodwrot/centralized/assets/prose/human
            ref: "{{ .var.CENTRALIZED_ASSETS_PROSE_HUMAN_REF }}"
            filepath: shared/license/LICENSE
          dest: LICENSE
      renderTemplates:
        - source:
            url: gitlab.com/konradodwrot/centralized/assets/prose/human
            ref: "{{ .var.CENTRALIZED_ASSETS_PROSE_HUMAN_REF }}"
            filepath: "prose/repos/{{ .var.repo }}/README.md.ontoRepo.tpl"
          dest: README.md

  'generic/filesUntracked':
    type: repo-git-untracked
    options:
      autoDiscover: false
    include:
      renderTemplates:
        - source:
            url: gitlab.com/konradodwrot/centralized/assets/prose/common
            ref: "{{ .var.CENTRALIZED_ASSETS_PROSE_COMMON_REF }}"
          options:
            skipAutoGeneratedHeader: true
          <<<:
            - source: "prose/repos/{{ .var.repo }}/purpose.md"
              dest: assets/docs-agents/purpose.md
            - source: templates/data
              dest: assets/data
              options:
                skipAutoGeneratedHeader: false
              <<<:
                - source: makefile-agents.md.ontoRepo.tpl
                  dest: makefile.agents.md
                - source: repo-structure.md.ontoRepo.tpl
                  dest: repo-structure.md
        - source:
            url: gitlab.com/konradodwrot/centralized/assets/prose/ai
            ref: "{{ .var.CENTRALIZED_ASSETS_PROSE_AI_REF }}"
            filepath: "prose/repos/{{ .var.repo }}/AGENTS.md.ontoRepo.tpl"
          dest:
            - CLAUDE.md
            - path: AGENTS.md
              options:
                renderReferencedFiles: true

  'generic/env':
    type: repo-git-untracked
    options:
      autoDiscover: false
    include:
      renderTemplates:
        - source:
            url: .
            filepath: .che/tpl/repo-git-tracked/env.tpl
          dest:
            - path: .env
              options:
                writeType: mergeUpsert

  'generic/deps':
    type: repo-git-untracked
    options:
      autoDiscover: false
    include:
      installPackages:
        - make
        - lefthook
        - yq
        - glab

##[<] 🤖🤖